name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Tests
        run: |
          cd tests
          docker-compose up -d
          deno test -A --coverage=cov integration
          deno coverage --lcov --exclude=tests ./cov > ../cov.lcov

      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          name: dami
          files: cov.lcov

  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Lint
        run: deno lint

      - name: Formatter
        run: deno fmt --check
