name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2

      - name: Unit
        run: |
          cd tests
          docker-compose up -d
          deno test --allow-net --allow-env unit

      - name: Integration
        run: |
          cd tests
          docker-compose up -d
          deno test --allow-net --allow-env integration/connect_and_login_.ts
          deno test --allow-net --allow-env integration/events_that_send_output_test.ts
          deno test -A integration/send_action_and_get_event_test.ts
          deno test -A integration/all_together_now_test.ts

  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Lint
        run: deno lint --unstable

      - name: Formatter
        run: deno fmt --check