name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Unit
        run: |
          cd tests
          docker-compose up -d
          deno test --allow-net --allow-env unit

      - name: Integration
        run: |
          cd tests
          docker-compose up -d
          deno test -A integration

  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Lint
        run: deno lint

      - name: Formatter
        run: deno fmt --check
