name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Unit
        run: deno test --allow-net --allow-env tests/unit

      - name: Integration
        run: deno test --allow-net --allow-env tests/integration

  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

#      - name: Lint
#        run: deno lint --unstable

      - name: Formatter
        run: deno fmt --check