name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Unit
        run: |
          cd tests
          docker-compose up -d
          deno test --allow-net --allow-env --coverage=unit_cov unit
          deno coverage --lcov unit_cov --exclude=tests > unit.lcov

      - name: Integration
        run: |
          cd tests
          docker-compose up -d
          deno test -A --coverage=integration_cov integration
          deno coverage --lcov integration_cov --exclude=tests > integration.lcov
      
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          name: dami
          files: tests/integration.lcov,tests/unit.lcov

  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Lint
        run: deno lint

      - name: Formatter
        run: deno fmt --check
